# Generated by Django 3.2.5 on 2021-08-07 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Progect',
            new_name='Project',
        ),
    ]
